apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: react-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react-app-registry
  policy:
    semver:
      range: ">=0.1.0"
