apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: react-app-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: react-app
  policy:
    semver:
      range: "1.0.0-0"  # Adjust this according to your image tag naming scheme
